CREATE TABLE medication (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    medicine_id INTEGER REFERENCES medication_list(id) ON DELETE CASCADE NOT NULL,
    dog_id INTEGER REFERENCES dog_profile(id) ON DELETE CASCADE NOT NULL,
    dosage_amount TEXT NOT NULL,
    dosage_unit TEXT NOT NULL,
    medication_note TEXT NOT NULL,
);