CREATE TABLE reminders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dog_id INTEGER REFERENCES dog_profile(id) ON DELETE CASCADE NOT NULL,
    reminder_name TEXT NOT NULL,
    reminder_date DATE NOT NULL,
    repeat BOOLEAN,
    reminder_type TEXT NOT NULL,
    reminder_note TEXT NOT NULL
);