CREATE TABLE vaccines (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dog_id INTEGER REFERENCES dog_profile(id) ON DELETE CASCADE NOT NULL,
    vaccine_name TEXT NOT NULL,
    serial_number TEXT,
    expiration_date DATE NOT NULL
);